import os
import sqlite3
class doctores:
    def __init__(self):
        self.Especialidad = ""
        self.Doctor = ""

    def especialidades(self):
        con1 = sqlite3.connect("pacientes.s3db")
        cursor = con1.cursor()
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (1,'Alergia e Inmunología','Dr. Félix César Ortiz Herrera' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (2,'Anestesiología','Dr. Félix César Ortiz Herrera' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (3,'Anestesiología','Dra. Socorro Bedregal Casapia' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (4,'Cardiología','Dra. María Gabriela Zavala Vinces' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (5,'Cardiología','Dr. William Pompeyo Mora López' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (6,'Cir. Torácica y Cardiovascular','Dr. Rodolfo Jesús Alarcón Pinto' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (7,'Cir. Torácica y Cardiovascular','Dr. Rafael Arrarte Congrains' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (8,'Cirugía Coloproctológica','Dr. Edgar Rivera Díaz' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (9,'Cirugía de Cabeza y Cuello','Dr. Ricardo Rene Gomez Galindo' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (10,'Cirugía de Cabeza y Cuello','Dr. Luis Ricardo Marca Bueno' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (11,'Cirugía General','Dr. Teodoro Guillermo Vargas Bernal' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (12,'Cirugía General','Dr. Pedro Manuel Tamayo Tapia' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (13,'Cirugía General y Oncológica','Dr. Luis Enrique Medina Fernández' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (14,'Cirugía General y Oncológica','Dr. Adolfo Lucio Morán Cárdenaz' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (15,'Cirugía Oncológica','Dr. Walter Grimaldo Fernandez Mendoza' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (16,'Cirugía Oncológica','Dr. Edwin Jesús Gonzáles Chávez' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (17,'Cirugía Pediátrica','Dr. Jorge Valdivia Tejada' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (18,'Cirugía Plastica y Reparadora','Dra. Segunda Pascuala Rubio Barrios' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (19,'Cirugía Plastica y Reparadora','Dr. Salvador Rodríguez Suca' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (20,'Dermatología','Dra. Lilia Zapata Carcamo' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (21,'Dermatología','Dra. Claudia Karen Salas Ortega' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (22,'Endocrinología','Dr. Ricardo Paolo Jiménez Orbegoso' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (23,'Endocrinología','Dr. Fernando Maximiliano Beltrán Castañeda' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (24,'Gastroenterología','Dra. Amparo Albina Medina Velarde' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (25,'Gastroenterología','Dr. Luis Arce Cordero' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (26,'Geriatría','Dra. Miriham Esperanza Camargo Pantoja' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (27,'Ginecología y Obstetricia','Dra. Rina Eleana Cuadros Salas' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (28,'Ginecología y Obstetricia','Dra. María Elena Esquivel Gonzáles' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (29,'Hematología','Dr. Víctor Raúl Rivera Gallegos' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (30,'Hematología','Dr. Manuel Orlando Rivas Chávez' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (31,'Infectología','Dr. Mario Cornejo Giraldo' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (32,'Medicina Física y Rehabilitación','Dra. Ruth Yubana Vera Luna' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (33,'Medicina Física y Rehabilitación','Dr. Siles Reynel Rodriguez Rodríguez' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (34,'Medicina General','Dr. César Arturo Gonzáles Pérez' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (35,'Medicina General','Dr. Alberto Bivian Salinas Portugal' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (36,'Medicina Intensiva','Dr. Rafael Fredy Tapia Pérez' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (37,'Medicina Intensiva','Dr. Miguel Barreda de la Cruz' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (38,'Medicina Intensiva Pediatrica','Dr. Víctor Hugo Calderón Arenas' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (39,'Medicina Interna','Dra. Luz Mercedes Mujica Calderón' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (40,'Medicina Interna','Dra. Luz * Mujica Calderón' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (41,'Medico Cirujano','Dr. Jorge Perea Espinoza' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (42,'Nefrología','Dr. Raúl Hernán Hinojosa Obando' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (43,'Nefrología','Dr. Jorge Erman Sánchez Sánchez' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (44,'Neumología','Dr. Miguel Fernando Farfán Delgado' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (45,'Neumología','Dr. Arturo Recabarren Lozada' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (46,'Neurocirugía','Dra. Marleny Isabel Llerena Velarde' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (47,'Neurocirugía','Dr. Víctor Gamero Ramírez' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (48,'Neurología','Dra. Yanet Astete Juarez' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (49,'Neurología','Dra. Jesús Yeliza Jovic Muñoz' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (50,'Nutricionista','Lic. Yanett Ccorahua Meza )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (51,'Nutricionista','Lic. Jesús Martinez Rodriguez' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (52,'Obstretricia','Obs. Patricia Valdivia Carazas' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (53,'Obstretricia','Obs. Eliana Cáceres Cáceres' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (54,'Odontología','Dr. Jaime Velarde Flores' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (55,'Oftalmología','Dra. Milagros Torres Zavala' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (56,'Oftalmología','Dra. Lucia Fajardo Karlo' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (57,'Oncologia Medica','Dr. Renzo Alvarez Barreda' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (58,'Oncologia Medica','Dr. Hernán David Morón Escobar' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (59,'Ortopedia y Traumatología','Dr. Walter Juan Vargas Rodríguez' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (60,'Ortopedia y Traumatología','Dr. Víctor Clodoaldo Salas Corrales' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (61,'Otorrinolaringología','Dra. Gina Elisa Chávez Torres' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (62,'Otorrinolaringología','Dr. Roberto Orlando Núñez Quiroz' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (63,'Pediatría','Dra. Olga Rocio Huaman Prado' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (64,'Pediatría','Dra. Nuvia Leonor Valdivia Málaga' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (65,'Psicología','Dra. Mileny Pamea Gastulo Vera' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (66,'Psicología','Dra. Elsa Flora Rodríguez Valero' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (67,'Psiquiatría','Dra. Carla Elizabeth Málaga Pinto' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (68,'Psiquiatría','Dr. Víctor Emilio Valdivia Murillo' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (69,'Radiología','Dra. Ivonne Elizabeth Rodríguez Fernández' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (70,'Radiología','Dra. Alejandra Mercado Ojeda de Calla' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (71,'Reumatología','Dra. Ruth Patricia Poblete Huertas' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (72,'Reumatología','Simón Alfredo Gutiérrez Chávez' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (73,'Urología','Dr. Roger Hugo Gutiérrez Córdova' )")
        cursor.execute("insert into Doctores (Codigo, Especialidad, Doctor) VALUES (74,'Urología','Dr. Luciano Benjamin Torrico Herrera' )")
        
        
        
        con1.commit()
        print("//////////////////////////////////////////////////////////////////")
        input("-------------Presione enter para regresar al menu-----------------")
        os.system("cls")
        con1.close()


    def mostrar_d(self):
        os.system("cls")
        print("\t============Especialidades CLINICA SAN JUAN DE DIOS==============")
        con1 = sqlite3.connect("pacientes.s3db")
        cursor = con1.cursor()
        cursor.execute("SELECT * from doctores")
        for i in cursor:
            print("============================================================")
            print("codigo:" ,i[0])
            print("Especialidad:" ,i[2])
            print("Medico:" ,i[3])
        print("/////////////////////////////////////////////////////////////////////////")
        input("--------------------Presione enter para regresar al menu------------------")
        os.system("cls")
        con1.close()

